apiVersion: batch/v1
kind: CronJob
metadata:
  name: placeholder
spec:
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
