apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      initContainers:
        - name: prepare-write-dirs
          command:
            - /bin/sh
          args:
            - -ec
            - |
              echo "Skipping Bitnami prepare-write-dirs (using official image with writable rootfs)"
              mkdir -p /opt/keycloak/data/import
