apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    # Add unique label to make this service's selector different from keycloak-headless (ADR-0010)
    keycloak.service/variant: http
