apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    # Add unique label to make this service's selector different from headless
    # Both services still select the same pods, but selectors are now unique
    postgresql.service/variant: primary
