apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  template:
    metadata:
      labels:
        # Add unique label to differentiate service selectors
        # This label is added to the regular service selector but not headless
        postgresql.service/variant: primary
