apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
spec:
  template:
    spec:
      containers:
      - name: indexer
        env:
        - name: RABBITMQ_RETRY_DELAY
          value: "0"
        - name: RABBITMQ_RETRY_LIMIT
          value: "0"
