apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
spec:
  template:
    spec:
      containers:
        - name: cert-manager-cainjector
          # Add tcpSocket probes on metrics port (9402)
          # The cainjector doesn't expose an HTTP healthz endpoint,
          # but it does expose metrics on port 9402 which we can use
          # for health checking via tcpSocket probes
          livenessProbe:
            tcpSocket:
              port: 9402
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 9402
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
