apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
spec:
  template:
    spec:
      containers:
        - name: cert-manager-controller
          # The chart only has livenessProbe - we need to add readinessProbe
          # for AKS Automatic safeguards compliance
          # Both use /livez on the healthz port (9403)
          readinessProbe:
            httpGet:
              path: /livez
              port: 9403
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
